### ISSUE TITLE
ItemsAdder compitability

### ISSUE THREAD

**Issue by freezyXD** [The-Zandrax/NoMoreCooked#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a ability to configure ItemsAdder food in config

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by The-Zandrax** [comment]
Thanks for the suggestion 

**ItemsAdder support** added in **NoMoreCooked 0.0.8**

First integration, please report any bugs

I hope you like it
