### ISSUE TITLE
More types of food

### ISSUE THREAD

**Issue by OODEK** [The-Zandrax/NoMoreCooked#12]
**Is your feature request related to a problem? Please describe.**
It is not possible to add more types of food in the config

**Describe the solution you'd like**
I would like it to be possible to add other types of foods in the settings

**Describe alternatives you've considered**
For example raw foods or wheat

**Additional context**
![image](https://github.com/user-attachments/assets/3d09e465-3e01-479c-a7f9-3307bed5bacb)

**Comment by The-Zandrax** [comment]
Hello !

Unfortunately I don't have the time to integrate a system where you can add your own foods in the config as I'm going on vacation tomorrow. However, I'll add what you've just asked me and deploy the update by this evening

**Comment by The-Zandrax** [comment]
The food items you request have been implemented **in version 0.0.9c of NoMoreCooked** available on Spigot.

I hope you enjoy it, thanks for your suggestions and reports, feel free to open further issues if you have a problem or suggestion, I'll do my best to help. I'll be back in early September. Have a nice day!

**Comment by The-Zandrax** [comment]
Thank you for the donation, i appreciate that.

These foods are indeed missing, I'll add them when I get back from vacation, so I'm reopening the Issue. 

I would also like to thank you for the various clear and detailed reports, I will also take care of them on my return.

**Comment by The-Zandrax** [comment]
Foods added in version **0.0.96 of NoMoreCooked** available on Spigot. 

Thanks for opening up all these OODEK issues :)

Have a nice day!
