### ISSUE TITLE
When it is eaten, the entire stack disappears

### ISSUE THREAD

**Issue by OODEK** [The-Zandrax/NoMoreCooked#16]
**Describe the bug**
When there is more than one expired food in a stack, when it is eaten, the entire stack disappears.

**To Reproduce**
Eating foods in stack.

**Expected behavior**
I understand that I should only consume 1

**Screenshots**
I have the following 3 expired foods in stack:
![image](https://github.com/user-attachments/assets/7b052909-c37d-4f5f-aae8-06ecbd22c140)

When I eat 1, all 3 disappear (screenshot after eating only 1):
![image](https://github.com/user-attachments/assets/891a4c9b-3362-4b61-9ab5-e648c8072f94)

**Minecraft Version:**
- 1.20.4

**Server Version:**
 - Paper 1.20.4

**Plugin Version**
- NoMoreCooked-0.0.9c-RELEASE

**Comment by The-Zandrax** [comment]
Problem solved in version **0.0.96 of NoMoreCooked** available on Spigot. 

If you encounter other problems, don't hesitate to reopen another issue or reply to this one if it concerns this problem.

Have a nice day !
