### ISSUE TITLE
Async inventory modification

### ISSUE THREAD

**Issue by OODEK** [The-Zandrax/NoMoreCooked#17]
**Describe the bug**
I have the MechanicsCore plugin installed and set the setting to "auto-checker-interval: 300" (every 5 minutes)

Every time I check, the MechanicsCore plugin shows me the following error for each food item in the inventory.

However, everything works normally, it's just that the message is a bit annoying, which is why I have the check in 5 minutes.

**To Reproduce**
Install the MechanicsCore plugin along with NoMoreCooked and wait for the check

**Expected behavior**
The ideal would be for the error not to appear since it messes up the console and logs.

**Screenshots**
![image](https://github.com/user-attachments/assets/c9dd6ca6-f00d-4c32-9d9d-2c4d9c89aea1)

**Minecraft Version:**
- 1.20.4

**Server Version:**
 - Paper 1.20.4

**Plugin Version**
- NoMoreCooked-0.0.9c-RELEASE
- MechanicsCore-3.4.8

**Comment by The-Zandrax** [comment]
Problem solved in version **0.0.96 of NoMoreCooked** available on Spigot. 

If you encounter other problems, don't hesitate to reopen another issue or reply to this one if it concerns this problem.

Have a nice day !
