### ISSUE TITLE
The item in your hand is not compatible when use "/nmc set spoiled"

### ISSUE THREAD

**Issue by OODEK** [The-Zandrax/NoMoreCooked#18]
**Describe the bug**
With some foods, using the command "/nmc set spoiled" tells me that the object is not supported.

**To Reproduce**
In my case I have used beef food, but it happens with others.

**Expected behavior**
You should set the food as expired just like with cooked beef or other foods that do work.

**Screenshots**
With a food that doesn't work:
![image](https://github.com/user-attachments/assets/f9f7eac3-2db9-4fbe-a8e7-a4a4b991d7b2)

With one that does work:
![image](https://github.com/user-attachments/assets/954825af-ef06-429f-a284-ad9cbc11633c)

**Minecraft Version:**
- 1.20.4

**Server Version:**
 - Paper 1.20.4

**Plugin Version**
- NoMoreCooked-0.0.9c-RELEASE

**Comment by The-Zandrax** [comment]
Problem solved in version **0.0.96 of NoMoreCooked** available on Spigot. 

If you encounter other problems, don't hesitate to reopen another issue or reply to this one if it concerns this problem.

Have a nice day !
