### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by OODEK** [The-Zandrax/NoMoreCooked#19]
**Describe the bug**
I'm using the WeaponMechanics plugin and when I kill a mob with a weapon, I get an error in the console.

It is not blocking, but it is annoying that the error appears in the console.

**To Reproduce**
Install the WeaponMechanics plugin and kill a mob with a weapon.

**Expected behavior**
The message should not appear in the console.

**Screenshots**
![image](https://github.com/user-attachments/assets/d09ac30d-5ab3-40ed-a02d-5585aeb3dcc9)

**Minecraft Version:**
- 1.20.4

**Server Version:**
 - Paper 1.20.4

**Plugin Version**
- NoMoreCooked v0.0.9c-RELEASE
- WeaponMechanics-3.4.9

**Comment by The-Zandrax** [comment]
Problem solved in version **0.0.96 of NoMoreCooked** available on Spigot. 

If you encounter other problems, don't hesitate to reopen another issue or reply to this one if it concerns this problem.

Have a nice day !
