### ISSUE TITLE
Can Load plugin In 1.16.5

### ISSUE THREAD

**Issue by MeooHunter** [The-Zandrax/NoMoreCooked#22]
**Describe the bug**
Log : (https://mclo.gs/LtyjhOY)

**To Reproduce**
Put plugin and run

**Expected behavior**
I want to fix this error

**Minecraft Version:**
- 1.16.5

**Server Version:**
 - Paper 1.16.5

**Plugin Version**
- NoMoreCooked-0.0.9c

**Comment by The-Zandrax** [comment]
Problem solved in version **0.0.96 of NoMoreCooked** available on Spigot. 

If you encounter other problems, don't hesitate to reopen another issue or reply to this one if it concerns this problem.

Have a nice day !
