### ISSUE TITLE
Hopper and the furnace

### ISSUE THREAD

**Issue by AMS-ABSTAND** [The-Zandrax/NoMoreCooked#23]
**To Reproduce**
If you place a hopper under a furnace, then the things are not included in the plugin and therefore have no expiry time

**Minecraft Version:**
1.21

**Server Version:**
paper 1.20.6

**Plugin Version**
0.0.96c

**Comment by The-Zandrax** [comment]
Hello, thank you for opening this report.

I tried to reproduce your environment, as there is an inconsistency between the versions of the report, I did both.

In both cases I get no incompatibility or problem concerning Hoppers and Expiry System.

I think there must be other variables in this environment, perhaps a plugin acting on the hoppers could interfere, could you tell me if this is possible?

It's also possible that your plugin configuration is different from my tests. Could you send me your config.yml? 

Then make sure you have the latest version of NoMoreCooked, as this is the latest update, but according to your report, you do have the correct version.

Looking forward to hearing from you.

Have a nice day!
