### ISSUE TITLE
fridge can't be crafted

### ISSUE THREAD

**Issue by DrJekyllH** [The-Zandrax/NoMoreCooked#25]
**Describe the bug**
fridge can't be craft on the craft table

**To Reproduce**
put materials for crafting the fridge on the craft table

**Expected behavior**
player can craft and get the fridge

**Screenshots**

![image](https://github.com/user-attachments/assets/833efa52-63cf-4737-ad11-ffe84f7d8f63)
![image](https://github.com/user-attachments/assets/755f90c3-8401-48af-ac3e-435ddf43be91)
![image](https://github.com/user-attachments/assets/68dab3c8-f1ed-4cb0-9d17-c188dc745823)
![image](https://github.com/user-attachments/assets/03fb9645-d1bc-468e-b8b7-4c7ab333a062)

**Minecraft Version:**
- 1.21

**Server Version:**
 - Paper 1.21

**Plugin Version**
- NoMoreCooked-0.0.98-RELEASE

**Comment by The-Zandrax** [comment]
Thanks for reporting the problem, it's fixed in version **0.0.98b of NoMoreCooked** available on Spigot. 

I had made a logical error regarding the verification of existing crafts when registering crafts.

Have a nice day !
