### ISSUE TITLE
Expirable/Edible Cooked Food Drops

### ISSUE THREAD

**Issue by CantBeKarma** [The-Zandrax/NoMoreCooked#3]
**Is your feature request related to a problem? Please describe.**
Perhaps just a slight situational "problem", would more so be a neat addition/feature. When an animal mob dies via fire (such as fire aspect) it drops "Cooked" versions, currently this plugin doesn't support those drops and doesn't make them editable (expirable). (see; https://minecraft.fandom.com/wiki/Cooked for a list)

**Describe the solution you'd like**
Make it so that the cooked drops from mobs are also set to expire/editable automatically just like cooking them.

**Describe alternatives you've considered**
Can't say I've thought of alternatives, pretty straight forward above!

**Additional context**
I had just restarted and tested the newest release to check that it's actually working from the prior bug report I submitted and it worked perfectly except I went ahead and killed a Pig with Fire Aspect and it dropped the Cooked version but it wasn't set to expire/editble. Just normal cooked food.

**Comment by The-Zandrax** [comment]
Thanks for the report !

The feature has been added to **NoMoreCooked 0.0.8**.

Currently, this supports when an entity is killed with the Fire Aspect enchantment and that entity drops cooked food.

Rereading the suggestion, I notice that I omitted to add support when an entity is killed by fire as a general rule.

I'll leave the suggestion open until I implement support for this case too.

**Comment by The-Zandrax** [comment]
This is now implemented. 

**In version 0.0.8a**, cooked foods dropped by entities that have been killed by fire, lava, etc, are affected by the expiration system.

Thanks for your suggestion! If you have any other requests, please feel free to open other issues.

Have a nice day !
