### ISSUE TITLE
If you use emeralds to trade with villagers for cooked food it doesnt use the expiration system

### ISSUE THREAD

**Issue by quocyugi** [The-Zandrax/NoMoreCooked#4]
Is your feature request related to a problem? Please describe.
This is pretty common in my server now at first i thought that because trading emeralds for cooked food is very expensive but it seems that there's an emerald farm so they can almost infinitely do trades and get food not getting affected by the system
Describe the solution you'd like
detect food related tradings to add the expiration date

Describe alternatives you've considered
i couldnt think of any

Additional context

**Comment by quocyugi** [comment]
Is your feature request related to a problem? Please describe.
This is pretty common in my server now at first i thought that because trading emeralds for cooked food is very expensive but it seems that there's an emerald farm so they can almost infinitely do trades and get food not getting affected by the system
Describe the solution you'd like
detect food related tradings to add the expiration date

Describe alternatives you've considered
i couldnt think of any

Additional context

**Comment by The-Zandrax** [comment]
Thanks for the report! 

The feature has now been added with **version 0.0.8c of NoMoreCooked**.
You can also define a custom expiry time specific to exchanges with villagers.

Let me know if everything goes well with the villagers.

I'm aware of a display bug when left-clicking, with several items on the cursor, on the last item in the NPC's stock. You'll notice that the exchange window doesn't update when the NPC's stock runs out; you can close and reopen the window to force the update. I'll look into resolving this problem in the future.

I hope the addition satisfies you!
