### ISSUE TITLE
Core mechanics update

### ISSUE THREAD

**Issue by Boddebon** [The-Zandrax/NoMoreCooked#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1. Change the refrigerator from a shulker to a chest. (You can change the craft of the refrigerator)
2. To make it clear that the chest is a refrigerator, add the spawn of snow particles from it (which can be disabled)
3. Add the ability to add an expiration date based on the food itself. Example:
-- Bread : 8600 ticks
-- Cooked beef: 3600 ticks
-- and so on.
4. Spoiled food can be used in a composter

**Describe alternatives you've considered**
I don’t consider alternatives, I think it will add more opportunities to server developers.

**Additional context**
No

**Comment by The-Zandrax** [comment]
Thanks for the quality suggestion, 

I'm taking it on board and it will see the light of day, however, I'm currently working on a project that's taking up all my time, which should last until early/mid-July, so I'm not sure I'll be able to provide an update by then, but rest assured I'll update the plugin as soon as possible. 

Thanks again for the suggestion and have a nice day!

**Comment by Boddebon** [comment]
Are you currently working on a new plugin, if so I'd be very happy to know if it's already available so I can check it out?

**Comment by The-Zandrax** [comment]
No, I'm just preparing a server project, and even if some features will probably require the development of small custom plugins, I don't think I'll make them available to the public, as they're so insignificant and too specific to a given problem.

**Comment by Boddebon** [comment]
I’ll be glad to play on your server, if you don’t mind, can I somehow get social networks to monitor your server?

**Comment by The-Zandrax** [comment]
The server I'm currently working on isn't available yet. The social networks related to the project are not currently available either, I'll let you know once the social networks are available!

**Comment by The-Zandrax** [comment]
Hello! All your suggestions have been implemented in **version 0.0.9 of NoMoreCooked**. 

- The fridge craft can be customized and the choice between a chest and a shulker box is possible.
- Snow particles are now available and slightly customizable.
- All foods are now supported and can have an expiration that can be set for each food individually.
- Spoiled meats can now be used in a composter.

Thanks again for all your suggestions, don't hesitate to reopen issues if necessary.

Have a nice day!
