### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Vixulek** [The-Zandrax/NoMoreCooked#8]
Hello can you set the carrots to have the same eating time

**Comment by Vixulek** [comment]
So that potatoes, carrots etc also have a validity of use

**Comment by The-Zandrax** [comment]
Hello, your suggestion has now been integrated into **version 0.0.9 of NoMoreCooked**. 

- All foods are now supported and can have an expiration that can be set for each food individually

Thanks for your suggestion!

Have a nice day!
