### ISSUE TITLE
In some cases, this feature may not function properly

### ISSUE THREAD

**Issue by 73410** [The-Zandrax/NoMoreCooked#9]
**Describe the bug**
when cook with Furnace/Smoker, Press' q 'to throw the cooked food out, then pick it up, it will not expiate. 
or use Hopper to collect the food from the Furnace/Smoker , then put it into Inventory, it will not expiate either.

**Expected behavior**
In the above two situations, the food will expiate.

**Minecraft Version:**
- 1.21

**Server Version:**
 -  Paper 1.21

**Plugin Version**
- 0.0.9b

**Comment by The-Zandrax** [comment]
Hello, thanks for the report

I can see the problem, I'll try to fix it before Wednesday. That's the day I go on vacation, so I hope to be able to sort it out before I leave, but I'm running out of time at the moment to prepare for my departure and do other important tasks. 

If I can't fix the plugin before I leave, it'll be fixed around September 1.

Thank you in advance for your patience!

**Comment by The-Zandrax** [comment]
Solution found in version **0.0.96 of NoMoreCooked** available on Spigot. 

If you encounter other problems, don't hesitate to reopen another issue or reply to this one if it concerns this problem.

Have a nice day !
